name: Reusable Docker Build Workflow

on:
  workflow_dispatch:    # 수동 실행 가능
    inputs:
      environment:
        description: "Deployment environment (dev, test, prod)"
        required: true
        type: string
      gcp-region:
        description: "GCP region"
        required: false
        type: string
        default: "asia-northeast3"
      dockerfile-path:
        description: "Dockerfile path"
        required: false
        type: string
        default: "./Dockerfile"
      dockerfile-context:
        description: "Docker build context"
        required: false
        type: string
        default: "."
      gcr-repo:
        description: "GCR repository name"
        required: true
        type: string
      gcr-image:
        description: "application image"
        required: true
        type: string
        default : "hello-gke-service"
      build-args:
        description: "Docker build arguments"
        required: false
        type: string
        
  # workflow_call:
  #   inputs:
  #     environment:
  #       description: "Deployment environment (dev, test, prod)"
  #       required: true
  #       type: string
  #     gcp-region:
  #       description: "GCP region"
  #       required: false
  #       type: string
  #       default: "asia-northeast3"
  #     dockerfile-path:
  #       description: "Dockerfile path"
  #       required: false
  #       type: string
  #       default: "./Dockerfile"
  #     dockerfile-context:
  #       description: "Docker build context"
  #       required: false
  #       type: string
  #       default: "."
  #     gcr-repo:
  #       description: "GCR repository name"
  #       required: true
  #       type: string
  #     gcr-image:
  #       description: "application image"
  #       required: true
  #       type: string
  #       default : "hello-gke-service"
  #     build-args:
  #       description: "Docker build arguments"
  #       required: false
  #       type: string
  #   secrets:
  #     GCP_PROJECT_ID:
  #       required: true
  #     GCP_SA_KEY: 
  #       required: true
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Validate environment
        run: |
          echo "==== Debug Information ===="
          echo "GitHub Reference: ${{ github.ref }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "GCP Region: ${{ inputs.gcp-region }}"
          echo "GCR Repository: ${{ inputs.gcr-repo }}"
          echo "GCR Image: ${{ inputs.gcr-image }}"
          echo "=========================="
          
          if [ "${{ inputs.environment }}" != "dev" ] && [ "${{ inputs.environment }}" != "test" ] && [ "${{ inputs.environment }}" != "prod" ]; then
            echo "Invalid environment: ${{ inputs.environment }}"
            exit 1
          fi
          echo "✅ Environment validation passed"

      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          token_format: 'access_token'  # 명시적으로 지정
          create_credentials_file: true # credentials 파일 생성

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet
      
      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          registry: 'asia-northeast3-docker.pkg.dev'
          username: _json_key
          password: ${{ inputs.environment == 'prod' && secrets.GCP_SA_KEY && secrets.GCP_SA_KEY }}
          
      # Build the Docker image
      - name: 'Build and push Docker container'
        run: |
          echo "Setting up Docker build variables..."
          DOCKER_TAG="${{ inputs.gcp-region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.gcr-repo }}/${{ inputs.gcr-image }}:${{ github.sha }}"
          echo "Docker tag: ${DOCKER_TAG}"
          
          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            . 2>&1 | tee build.log

          echo "Pushing Docker image to registry..."
          docker push "${DOCKER_TAG}" 2>&1 | tee push.log

      # 작업 완료 후 상태 보고
      - name: Workflow Summary
        if: always()
        run: |
          echo "==== Workflow Summary ===="
          echo "Environment: ${{ inputs.environment }}"
          echo "Image: ${{ inputs.gcp-region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.gcr-repo }}/${{ inputs.gcr-image }}:${{ github.sha }}"
          echo "Build Status: ${{ job.status }}"
          echo "=========================="
      
